## Hardware summary overview {#sec-hardware-summary-overview}

This part is meant to give an overview of the hardware, more detailed description should be given in the 03_product_dvt/hardware_overview.md file.

Give an overview of the hardware, what it does (intended use), how it was produced, and, if relevant, the research for which it has been used.
Write as much as possible for a general audience.
That is, explain what the project is and what it is for, before you get into the technical details.
Describe how the hardware was implemented/created, with relevant details of the architecture and design, including general materials.

You may also describe any variants and associated implementation differences, as well as give numbers about how many hardware were made and by whom.

A schema, a picture or a video may be added here: Photos help people understand what your project is and how to put it together.
It’s good to publish photographs from multiple viewpoints and at various stages of assembly.
If you don’t have photos, posting 3D renderings of your design is a good alternative.
Either way, it’s good to provide captions or text that explain what’s shown in each image and why’s it’s useful.

> Example:
>
> The project [BCN3D Moveo](https://github.com/BCN3D/BCN3D-Moveo/) is an open source robotic arm that everyone should be able to replicate - with or without modification - at home without the need for highly technical knowledge and expensive materials.
> The robotic arm will support several of the existing training itineraries: mechanical design, automation, industrial programming, etc.
>
> Pedal powered machine: https://codeberg.org/openmakeXlowtech/PedalPoweredMachine-4fablab : photo + "size: about 700x1000 mm, table is 1100 mm high."

------------------------------------------------------------------------

**Sources**

@sec-open-next-work, @sec-journal-of-open-hardware, @sec-source-turing, @sec-source-OKH, @sec-source-oshwa-bp
