## Product design and CAD files {#sec-product-design-and-cad-files}

Computer assisted design is usually used to create structures from the models.
The designs should be best provided in their raw format (Native formats, best for making changes), an editable standard format (Neutral formats,  interchange and export formats that can be opened or imported by other CAD programs), and a exported format (Auxiliary format, ready-to-view outputs, may be used for production or for study the design) used for manufacture.
For example, a fusion .f3d file, a Step file and a STL file.
Always indicate what software (including version number) was used to create the file (see @sec-software-used-for-development).

CAD files may contain different parts/modules in a single file.
It is good practices to export an assemble view and an exploded view of the hardware (if the software does this).
These views may be included in the BOM overview and the assembly instructions.

Ideally, your Open Source Hardware project would be designed using a free and Open Source Software application, to maximize the ability of others to view and edit it.
For better or worse however, hardware design files are often created in proprietary programs and stored in proprietary formats.
It is still essential to share these original design files; they constitute the original “source code” for the hardware.
They are the very files that someone will need in order to contribute changes to a given design.
Also try to name files with a clear name, add material specification and number of pieces, the name of the file should correspond to the name of the part in the BOM (@sec-product-build-bill-of-material).

### Brief advice for object design:

-   Design the project to be easily adaptable for common differences (for example metric vs imperial units) and adaptations.
-   Make the design parametric (for example make product length and width dependent on one single parametric unit).
-   Utilize asymmetric design to make parts fit together uniquely and avoid miss-assemblies.
-   Use automation tools of the used programs
- Use free and open-source software design (CAD) tools where possible. If that’s not feasible, try to use low-cost and/or widely-used software packages.
- Use standard and widely-available components, materials, and production processes. Try to avoid parts that aren’t available to individual customers or processes that require expensive setup costs.

### CAD for electronics, PCB design

To reuse a electrical design, it should provide information consist of:

1.  Preferable file format

-   Editable file formats that could be:
    -   Source formats such as .gbr, .lib format\
    -   Neutral formats such as Kicad_mod, kicad_pcb

2.  Preferable open-source software

-   Tiny CAD
-   KiCAD
-   ADINA

> Examples:
>
> [Nasa-JPL, source files](https://github.com/nasa-jpl/open-source-rover/tree/master/electrical/pcb/arduino_uno_sheild/gerbers/rev_b)\*
>
> [AmbovVent, Neutral files](https://github.com/AmboVent-1690-108/AmboVent/tree/master/1-Electronics)\*

### CAD for structure models

Model design should be provided in a format that can be used to manufacture each piece: usually STL and STEP file for 3D objects, and SVG file for 2D design, electrical design can be shared in the editable format directly.
These formats are often easier to preview, and will help understand the structural/electrical design.

Note that the file is often not sufficient to reproduce one piece and manufacturing information must be given, as explained in @sec-product-build-manufacturing-instructions.

### Editable file format

An editable file format is a standard way that information is encoded for storage and allows the makers to study, modify the geometry of a model and reuse it.

To reuse a design model, it should provide information consist of:

1.  Preferable 3D/2D file format

-   Editable file formats that could be:
    -   Native formats such as .FCStd format of FreeCAD
    -   Neutral formats such as STEP files

2.  Preferable open-source software

-   OpensCAD
-   Inkscape
-   FreeCAD

> Example of editable file formats:
>
> -   [Farmbot, Native CAD files](https://genesis.farm.bot/v1.5/Extras/cad)\*
>
> -   [MIT Emergency Ventilator, Neutral CAD files](https://e-vent.mit.edu/resources/downloads/)\*
>
> -   Types of CAD format of [transmagic](https://transmagic.com/cad-formats/)\*

------------------------------------------------------------------------

**Sources**

@sec-open-next-work, @sec-source-docubricks, @sec-source-oho, @sec-source-oshwa-bp
