---
editor: 
  markdown: 
    wrap: 72
---

# Readme as entry door {#sec-readme}

Your Open Source Hardware project should include a general description
of the hardware’s identity and purpose (\@sec-vision-and-motivation),
written as much as possible for a general audience. A good photo or
rendering can help a lot here (see @sec-hardware-summary-overview).

Think about your audience when writing the OSH documentation, and tailor
the documentation (and design) to them. You may have different entry
points for educators, DIY makes, peer scientists, professional engineers
and so on. You can start your documentation with a description of some
pathways and links tailored to specific users. You should indicate at
least an absolute URL pointing to a webpage or to the home repository of
the documentation or its archive (in full text, not as a hidden link,
such that a printed version of the documentation would link to the
documentation).

Your project might be reused by people with different skills, roles,
objectives, and socio-economic and cultural environments. Because of
this it can be useful to create a list of skills that are required to
build (manufacture @sec-product-build-manufacturing-all, and assemble
@sec-product-build-assembly-skills-and-tools) or use the hardware
(@sec-user-skills). Someone trying to build it from scratch, for
example, will require specific set of prior knowledge, skills, and
tools. A different set is needed to perform maintenance tasks. An end
user operating the assembled project might require an entirely distinct
skillsets (and documentation).

The readme usually starts with some main information about the hardware
(name, development stage, subject area, keywords, license, languages
available, latest change, date of creation). It may be good to have that
information both in the readme and in a computer readable format, like a
OKH metadata file.

## *Type of hardware, subject area* {#sec-type-of-hardware-subject-area}

On top of keywords mentioned previously, one can report the Cpc
(**Cooperative Patent Classification)** class
(<https://worldwide.espacenet.com/classification>) of the hardware.

You also may indicate the purpose and/or maturity of the hardware and
its documentation to manage expectations.

> Examples: proof of principle, easy to make in educational workshop

------------------------------------------------------------------------

**Sources**

@sec-open-next-work, @sec-source-turing, @sec-source-docubricks,
@sec-source-OKH, @sec-source-okh-losh-version, @sec-source-oshwa-bp
