# Sources {#sec-sources}

## OpenNext work {#sec-open-next-work}

The work was presented in a template at.
<https://github.com/OPEN-NEXT/WP2.3-Guideline-and-template-for-documentation-of-OSH-design-reuse/tree/main>, based on the results provided as deliverable 2.6 at <https://github.com/OPEN-NEXT/WP2.3-Guideline-and-template-for-documentation-of-OSH-design-reuse/blob/main/Sources/Deliverable2_6%20_Final%20release%20of%20models%20and%20standards%20for%20design%20reuse_V4_20220930.pdf>

## OSH-dir-std work

The content of the 04_hardware folder is loosely derived from <https://github.com/hoijui/osh-dir-std/tree/main> in discussion with one of the author.

## Journal of open hardware {#sec-journal-of-open-hardware}

The journal of open hardware provides a template with several information required in hardware metadata papers.
We included some of the indication of the template into this guide.

## Journal hardwareX {#sec-journal-hardwareX}

The journal hardwareX provides a template with several information required in hardware metadata papers.
Todd Duncombe.
(2021).
HardwareX manuscript templates.
https://doi.org/10.5281/zenodo.5078227

## Turing way book {#sec-source-turing}

Content taken from The Turing Way Community.
(2025).
The Turing Way: A handbook for reproducible, ethical and collaborative research.
Zenodo. 
<https://doi.org/10.5281/zenodo.15213042>.
(shared under a CC-BY license).

A specific [chapter on OSH](https://book.the-turing-way.org/reproducible-research/open/open-hardware#what-is-the-source-of-open-source-hardware) and the linked chapter on [OS project documentation](https://book.the-turing-way.org/project-design/pd-overview/pd-overview-repro).
NB: The team behind this guide was involved in the redaction of these chapters.

## Docubricks {#sec-source-docubricks}

Docubricks is/was a metadata format providing best practices.
The elements in this book were found on a wayback machine copy of the website in January 2025: <http://web.archive.org/web/20250120163655/https://www.docubricks.com/best-practise-guide.jsp>

## Open know how manifest {#sec-source-OKH}

Open Know-How is all about sharing knowledge on how to make things.
The objective of this specification is to improve the open-ness of know-how for making hardware by improving the discoverability, portability and translatability of knowledge.\
<https://standards.internetofproduction.org/pub/okh/release/1>

## OKH - LOSH extension {#sec-source-okh-losh-version}

Open Know-How Specification for the Library of Open Source Hardware subtitle: OKH-LOSH.
<https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/OKH-LOSH.md>\
Only few addition were made from this source, as most of it is either very technical or too specialised.

## OHO know how {#sec-source-oho}

The open hardware observatory developed some best practices aimed at facilitating reviews of hardware.
This is particularly directed toward the technical aspect of the hardware project, including how to create BOM and document CAD files: <https://en.oho.wiki/wiki/Parts_list#Guidelines>, <https://en.oho.wiki/wiki/CAD_files>, <https://en.oho.wiki/wiki/Technical_drawings>

## OSHWA best practices  {#sec-source-oshwa-bp}

The OSHWA provides documentation on best practices for open hardware

<https://oshwa.org/resources/sharing-best-practices/>
